config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  resources :users, except: [:new]
  resources :cellphones

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  get 'contact', to: 'welcome#contact'

end

app/models/cellphone.rb
class Cellphone < ActiveRecord::Base
  
  after_save :phone_change_notification, if: :reference_changed?

  
  belongs_to :user
  
  
  validates :reference, presence: true, presence: {message: "está vacio, ingresa una!"}
  validates_presence_of :os, :user_id
  validates_length_of :reference, :os, minimum: 3
  
  private
  def phone_change_notification
    UserDevices.phone_change(self).deliver
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :cellphones, dependent: :destroy
  before_save {self.email = email.downcase}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :username, presence: true, length: {minimum: 3}
  validates :email, presence:true, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}, length: {maximum:105} 

  has_secure_password


  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !current_user
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
  
  
end

app/controllers/cellphones_controller.rb
class CellphonesController < ApplicationController
  
  before_action :set_cellphone, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  
  def index
    @cellphones = Cellphone.paginate(page: params[:page], per_page: 10)
  end
  
  def new
    @cellphone = Cellphone.new
  end
  
  def create
    @cellphone = Cellphone.new(cellphone_params)
    @cellphone.user = current_user
    if @cellphone.save
      flash[:notice] = "The phone was successfully created"
      redirect_to @cellphone
    else 
      render 'new'
    end
  end
  
  def show
  end

  def edit
  end
  
  def update
    if @cellphone.update(cellphone_params)
      flash[:notice] = "Successfully updated"
      redirect_to cellphones_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @cellphone.destroy
    flash[:notice] = "Phote successfully deleted"
    redirect_to cellphones_path
  end
  
  
  private
  def cellphone_params
    params.require(:cellphone).permit(:reference, :os)
  end
  
  def set_cellphone
    @cellphone = Cellphone.find(params[:id])
  end
  
  def require_same_user
    if current_user != @cellphone.user && !current_user.admin
      flash[:danger] = "You can only edit or delete your own devices"
      redirect_to root_path
    end
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have logged in as #{user.username}"
      redirect_to user
    else
      flash.now[:danger] = "Something is wrong with your user information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def show
  end
  
  def destroy
    @user.destroy
    flash[:notice] = "User have been destroyed successfully"
    redirect_to users_path
  end
  
  private 
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params 
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def home
  end
  
  def about 
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def gravatar_for(user, options={size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=retro"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cellphones/_cellphones.html.erb
<table>
  <thead>
    <tr>
      <th>Reference</th>
      <th>OS</th>
      <th>Owner</th>
      <th colspan=3></th>
    </tr>
  </thead>
  <tbody>
    <% obj.each do |cellphone| %>
    <tr>
      <%= div_for cellphone do %>
      <td><%= cellphone.reference %></td>
      <td><%= cellphone.os %></td>
      <td><%= cellphone.user.username if cellphone.user %></td>
      <% if current_user == cellphone.user %>
      <td>
        <%= link_to "Show", cellphone %>
        <%= link_to "Edit", edit_cellphone_path(cellphone) %>
        <%= link_to "Delete", cellphone_path(cellphone), method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
      <% end %>
      <% end %>
    <% end %>
    </tr>
  </tbody>
</table>
</br>

app/views/cellphones/_form.html.erb
<%= render 'shared/errors', obj: @cellphone %>

<%= form_for @cellphone do |f| %>
  <div>
    <%= f.label :reference %>
    <p><%= f.text_field :reference %></p>
  </div>
  <div>
    <%= f.label :os %>
    <%= f.select :os, ['Android', 'iOS', 'Windows Phone', 'Other'] %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>
  

app/views/cellphones/edit.html.erb
<h1>Edit Cellphone Data</h1>

<%= render 'form' %>

<%= link_to "Back to Index", cellphones_path %>

app/views/cellphones/index.html.erb
<h1>List of Cellphones</h1>

<%= will_paginate %>

<%= render 'cellphones', obj: @cellphones %>

<%= will_paginate %>

<%= link_to 'Back Home', root_path %> / <%= link_to 'Add New Phone', new_cellphone_path %>

app/views/cellphones/new.html.erb
<h1>Create new Cellphone</h1>

<%= render 'form' %>

<%= link_to 'Cellphone Index', cellphones_path %>

app/views/cellphones/show.html.erb
<h1> <%= @cellphone.reference %> Data</h1>

Reference:  <%= @cellphone.reference %></br>
OS: <%= @cellphone.os %></br>
Owner: <%= @cellphone.user.username %></br>
Created <%= time_ago_in_words @cellphone.created_at %> ago
</br></br>
<%= link_to "Back to Index", cellphones_path %> / <%= link_to "Edit", edit_cellphone_path(@cellphone) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

<div class="container">
  <%= link_to "HOME", root_path %>
  <% if !current_user %>
    <%= link_to 'Sign in', login_path %>
    <%= link_to "Sign Up", signup_path %>
  <% else %>
    <%= link_to 'Sign out', logout_path, method: :delete %>
    <%= link_to "#{current_user.email}", edit_user_path(current_user) %>
  <% end %>
</div>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2><%= pluralize(obj.errors.count, 'error') %> occurred</h2>
  <% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |error| %>
      <ul>
        <li><%= error %></li>
      </ul>
    <% end %>
  <% end %>
<% end %>

app/views/user_devices/phone_change.html.erb
<h1><%= @greeting %></h1>

<p>
  This email is to confirm that your phone has been changed.
</p>
<p>Check it out here: <%= link_to "My Phones", cellphone_url(@cellphone) %></p>

app/views/user_devices/phone_change.text.erb
<%= @greeting %>

This email is to confirm that your phone has been changed.

Check it out here: <%= link_to "My Phones", cellphone_url(@cellphone) %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for (@user) do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Your username..." %>  
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "your email..." %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <% if current_user && current_user.admin %>
  <p>
    <%= f.label :admin %>
    <%= f.check_box :admin %>
  </p>
  <% end %>
  <p>
    <%= f.submit (@user.new_record? ? "Sign Up":"Update Account")%>
  </p>
<% end %>
  
  

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>

<%= render 'form' %>

<%= link_to "Back", users_path %>

app/views/users/index.html.erb
<h1>Users List</h1>
<div style="text-align: center">

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Nº of Devices</th>
      <th>Profile Image</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.cellphones.count %></td>
      <td><%= gravatar_for(user, size:30) %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</br>
<%= link_to "Back Home", root_path %> / <%= link_to "Create new user", signup_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>


<%= link_to "Back", users_path %>

app/views/users/show.html.erb
<h1>Welcome to <%= "#{@user.username}'s" %> page</h1>

<%= gravatar_for(@user, size:150) %>

</br>
<h2><%= "#{@user.username} devices" %></h2>
<%= render 'cellphones/cellphones', obj: @user.cellphones %>

<%= link_to "Back", users_path %>

app/views/welcome/about.html.erb
<h1>ABOUT PAGE</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'Contact', contact_path %>

app/views/welcome/contact.html.erb
<h1>CONTACT PAGE</h1>

<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>

app/views/welcome/home.html.erb
<h1>HOME PAGE</h1>


<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Users', users_path %>
<%= link_to 'Cellphones', cellphones_path %>
<br>
<button type="button" onclick="document.getElementById('fecha').innerHTML = Date()">Fecha de Hoy?</button>
<p id="fecha"></p>

</br>
</br>

<%= truncate("Prueba de Truncate con separador", length: 15, separator: ' ') %>
Price is <%= number_to_currency(50) %> dollars
</br></br>
<p id="prueba">Cambiame al dar click en el botón</p>


<button type="button" onclick="document.getElementById('prueba').innerHTML = 'Que obediente, bien hecho!'">Click Me</button>
</br></br>

<!-- <img id="myImage" onclick="changeImage()" src="/assets/bulboff.png" height="180" width="100"> -->
<%= image_tag 'bulboff.png', width: "100", height: "180", onclick: "changeImage()", id: "myImage"%>


<script>
  function changeImage() {
    var image = document.getElementById('myImage');
    if (image.src.match('bulboff')) {
      image.src = "/assets/bulbon.png";
    } else {
      image.src = "/assets/bulboff.png";
    }
  }
</script>



<button type="button" onclick="document.getElementById('myImage').src = '/assets/bulbon.png'">Turn On</button>
<button type="button" onclick="document.getElementById('myImage').src = '/assets/bulboff.png'">Turn off</button>

</br></br>

<p id="p1">Cambia mi estilo con el botton</p>
<button type="button" onclick="changeStyle()">Change Style</button>
<script>
  function changeStyle() {
    var x = document.getElementById('p1');
    x.innerHTML = "Que Grande Eres!"
    x.style.fontSize = "25px";
    x.style.color = "red";
  }
</script>


<h2>ADIVINA EL ANIMAL</h2>
<p>Ingresa un aninal de orejas largas</p>
<input id="animal" onmouseleave="white()">
<button id="b1" onclick="animal()">Submit</button>
</br>
<%= image_tag "", id:"animalFoto", width:"", height:"" %>
<p id="r1"></p>
<script>
  function animal() {
    var x, image, respuesta;
    x = document.getElementById('animal').value;
    x = x.toUpperCase();
    image = document.getElementById('animalFoto');
    respuesta = document.getElementById('r1');
    respuesta.innerHTML = "Hola";
    document.getElementById('b1').innerHTML = "Bien";
    if (x == "BURRO") {
      image.width = "300";
      image.height = "300";
      image.src = "/assets/javier_bu.jpg";
      respuesta.innerHTML = "Este es un ejemplo... XD";
    } else {
      respuesta.innerHTML = "Intenta de nuevo";
    }
  } 

  function white() {
    document.getElementById('r1').innerHTML = "";
  }
</script>

</br>
<button type="button" onclick="pruebaApp()">CLICK ME</button>
</br></br>
<p id="pruebaFetch"></p>
<script>
  function pruebaApp() {
    var F = document.getElementById('pruebaFetch');
    F.style.fontSize = "40px";
    F.style.color = "blue";
    F.innerHTML = "PRUEBA FETCH";
  }
</script>